# -----------------------------------------------------------------
# サマリー:
# このDockerfileは、CUDA 11.0およびUbuntu 20.04をベースにしたface01_gpuイメージをビルドします。
# ユーザーの追加、必要なパッケージのインストール、環境設定を行い、Docker_INSTALL_FACE01.shスクリプトを実行してセットアップを行います。
# -----------------------------------------------------------------


FROM nvidia/cuda:11.0.3-base-ubuntu20.04
LABEL maintainer="y.kesamaru@tokai-kaoninsho.com"

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES utility,compute

ENV DEBIAN_FRONTEND noninteractive

RUN sed -i "s@# deb http://archive.canonical.com/ubuntu focal partner@deb http://archive.canonical.com/ubuntu focal partner@" /etc/apt/sources.list
RUN apt-get update \
    && apt-get install -y \
	software-properties-common \
	apt-utils \
	sudo \
	supervisor \
    build-essential \
    cmake \
    ffmpeg \
    fonts-mplus \
    git \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    libx11-dev \
    python3-dev \
    python3-tk \
    python3-pkg-resources \
    python3-venv \
    wget \
	cuda \
	libcublas-11-7 \
	libcublas-dev-11-7 \
	libcudnn8 \
	libcudnn8-dev \
	liblapack-dev \
	libopenblas-dev \
	nvidia-cuda-toolkit \
    language-pack-ja \
    fonts-noto-cjk \
    vim \
    libsm6 \
    libxext6 \
    libxrender-dev \
	&& rm -rf /var/lib/apt/lists/*

# configure
RUN locale-gen ja_JP.UTF-8
ENV LANG=ja_JP.UTF-8
ENV TZ=Asia/Tokyo
# add user
ARG DOCKER_UID=1000
ARG DOCKER_USER=docker
ARG DOCKER_PASSWORD=docker
RUN useradd -m \
  --uid ${DOCKER_UID} --groups sudo,video --shell /bin/bash ${DOCKER_USER} \
  && echo ${DOCKER_USER}:${DOCKER_PASSWORD} | chpasswd

WORKDIR /home/${DOCKER_USER}
RUN chown -R ${DOCKER_USER} ./
USER ${DOCKER_USER}

# Install FACE01
RUN mkdir /home/${DOCKER_USER}/FACE01_DEV
WORKDIR /home/${DOCKER_USER}/FACE01_DEV/

COPY face01lib /home/${DOCKER_USER}/FACE01_DEV/face01lib
COPY output /home/${DOCKER_USER}/FACE01_DEV/output
COPY noFace /home/${DOCKER_USER}/FACE01_DEV/noFace
# COPY images /home/${DOCKER_USER}/FACE01_DEV/images
COPY pyproject.toml /home/${DOCKER_USER}/FACE01_DEV/
COPY requirements_dev.txt /home/${DOCKER_USER}/FACE01_DEV/
COPY config.ini /home/${DOCKER_USER}/FACE01_DEV/

## Folder newly prepared from v1.4.09
COPY docs /home/${DOCKER_USER}/FACE01_DEV/docs
COPY example /home/${DOCKER_USER}/FACE01_DEV/example
# COPY tests /home/${DOCKER_USER}/FACE01_DEV/tests
COPY assets /home/${DOCKER_USER}/FACE01_DEV/assets

## Folders and files obsolete from v1.4.09
# COPY FACE01.py /home/${DOCKER_USER}/FACE01_DEV/
# COPY CALL_FACE01.py /home/${DOCKER_USER}/FACE01_DEV/
# COPY *.mp4 /home/${DOCKER_USER}/FACE01_DEV/

# COPY dlib-19.24.tar.bz2 /home/${DOCKER_USER}/FACE01_DEV/
COPY SystemCheckLock /home/${DOCKER_USER}/FACE01_DEV/
RUN echo ${DOCKER_PASSWORD} | sudo -S chown -R ${DOCKER_USER} /home/${DOCKER_USER}/FACE01_DEV
COPY preset_face_images /home/${DOCKER_USER}/FACE01_DEV/preset_face_images

COPY docker/Docker_INSTALL_FACE01.sh /home/${DOCKER_USER}/FACE01_DEV/
WORKDIR /home/${DOCKER_USER}/FACE01_DEV
RUN echo ${DOCKER_PASSWORD} | sudo -S chown ${DOCKER_USER} /home/${DOCKER_USER}/FACE01_DEV/Docker_INSTALL_FACE01.sh \
    && chmod +x /home/${DOCKER_USER}/FACE01_DEV/Docker_INSTALL_FACE01.sh \
    && /bin/bash -c /home/${DOCKER_USER}/FACE01_DEV/Docker_INSTALL_FACE01.sh \

# `--clean` see bellow
# [Have you done sudo python3 setup.py install --clean yet?](https://github.com/davisking/dlib/issues/1686#issuecomment-471509357)