# ベースイメージの選択
FROM nvidia/cuda:11.6.1-runtime-ubuntu20.04
LABEL maintainer="y.kesamaru@tokai-kaoninsho.com"

# 環境変数の設定
ENV DEBIAN_FRONTEND=noninteractive \
    LANG=ja_JP.UTF-8 \
    TZ=Asia/Tokyo \
    USER_HOME=/home/docker

# 必要なパッケージのインストールとロケール設定
RUN apt-get update && apt-get install -y \
    # CUDA関連
    libcudnn8 \
    # 線形代数関連
    liblapack3 \
    libopenblas-base \
    # dlib build
    build-essential \
    cmake \
    # 必要なツール
    wget \
    sudo \
    supervisor \
    git \
    vim \
    gedit \
    # Python関連
    python3 \
    python3-tk \
    python3-pkg-resources \
    python3-venv \
    # メディア関連
    ffmpeg \
    libavcodec58 \
    libavformat58 \
    libswscale5 \
    # X11ライブラリ関連
    libx11-6 \
    libsm6 \
    libxext6 \
    libxrender1 \
    # 言語サポート・フォント関連
    language-pack-ja \
    fonts-mplus \
    fonts-noto-cjk \
    locales tzdata && \
    locale-gen ja_JP.UTF-8 && \
    ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# ユーザー追加
ARG DOCKER_UID=1000
ARG DOCKER_USER=docker
ARG DOCKER_PASSWORD=docker
RUN useradd -m --uid ${DOCKER_UID} --home-dir ${USER_HOME} --groups sudo,video --shell /bin/bash ${DOCKER_USER} \
    && echo ${DOCKER_USER}:${DOCKER_PASSWORD} | chpasswd \
    && chown -R ${DOCKER_USER}:${DOCKER_USER} ${USER_HOME}

# ユーザーに切り替え
USER ${DOCKER_USER}
WORKDIR ${USER_HOME}/FACE01_DEV

# 必要なフォルダとファイルをコピー
COPY --chown=docker:docker face01lib /home/docker/FACE01_DEV/face01lib
COPY --chown=docker:docker output /home/docker/FACE01_DEV/output
COPY --chown=docker:docker noFace /home/docker/FACE01_DEV/noFace
COPY --chown=docker:docker example /home/docker/FACE01_DEV/example
COPY --chown=docker:docker assets /home/docker/FACE01_DEV/assets
COPY --chown=docker:docker preset_face_images /home/docker/FACE01_DEV/preset_face_images
COPY --chown=docker:docker pyproject.toml requirements_dev.txt config.ini /home/docker/FACE01_DEV/


# スクリプトのコピーと実行
COPY --chmod=0755 docker/Docker_INSTALL_FACE01.sh ${USER_HOME}/FACE01_DEV/
RUN /bin/bash -c ${USER_HOME}/FACE01_DEV/Docker_INSTALL_FACE01.sh
