name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches: '**'  # 全てのブランチでトリガー

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload docs to GitHub Pages
        uses: actions/upload-artifact@v4
        with:
          path: ./docs
          name: docs-for-gh-pages
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: docs-for-gh-pages
