name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - '**'  # 全てのブランチでトリガー

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  upload:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs  # ローカルで生成されたドキュメントが入っているディレクトリ
          name: github-pages
          retention-days: 1

  deploy:
    runs-on: ubuntu-22.04
    needs: upload

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: github-pages
