name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake
          sudo apt-get install -y build-essential
          sudo apt-get install -y libopenblas-dev liblapack-dev
          pip install -e .
          pip install -r requirements_dev.txt

      - name: Generate Sphinx documentation
        run: |
          sphinx-apidoc -f -o /home/terms/bin/FACE01_DEV/sphinx /home/terms/bin/FACE01_DEV
          sphinx-build -a -b html -E ./sphinx ./docs

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
          name: github-pages
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: github-pages
